version: '3.8'

services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    env_file: ./apps/reservations/.env

    command: yarn start:dev reservations
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    env_file: ./apps/auth/.env
    command: yarn start:dev auth
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    env_file: ./apps/payments/.env
    command: yarn start:dev payments
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
